version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always

  scraper:
    build:
      context: .
      dockerfile: scraper/Dockerfile
    container_name: scraper
    depends_on:
      - mongodb
    restart: on-failure
    tty: true
    stdin_open: true

  generador:
    build:
      context: .
      dockerfile: generador/Dockerfile
    container_name: generador
    depends_on:
      - mongodb
      - redis
    restart: on-failure
    tty: true
    stdin_open: true

  monitor:
    build:
      context: .
      dockerfile: monitor/Dockerfile
    container_name: monitor
    ports:
      - "5000:5000"
    restart: on-failure
    tty: true
    stdin_open: true

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    command: >
      redis-server
      --maxmemory 100mb                            
      --maxmemory-policy allkeys-lfu
    restart: always

  cache_monitor:
    build:
      context: .
      dockerfile: cache_monitor/Dockerfile
    container_name: cache_monitor
    ports:
      - "7000:7000"
    depends_on:
      - redis
    restart: on-failure
    tty: true
    stdin_open: true

  procesador:
    build:
      context: .
      dockerfile: procesamiento/Dockerfile
    container_name: procesador
    depends_on:
      - mongodb
    volumes:
      - ./salida:/app/salida
    restart: on-failure
    tty: true
    stdin_open: true
  pig:
    build:
      context: ./pig         
      dockerfile: Dockerfile 
    container_name: pig
    volumes:
      - ./salida:/data
    depends_on:
      - procesador
    tty: true
    stdin_open: true

